{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vertxapi.serviceAccountName" . }}
  labels:
{{ include "vertxapi.labels" . | nindent 4 }}
{{- end -}}
