vertx-api:
  enabled: true
  replicaCount: 1
  image:
    pullPolicy: Never
  service:
    type: NodePort
    nodePort: 30080
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  config:
    kafka_host: component-kafka
    kafka_port: 9092
    redis_host: component-redis-master
    redis_port: 6379

kafka:
  enabled: false
  replicas: 1
  persistence:
    size: 256Mi
  zookeeper:
    replicaCount: 1
    storage: 256Mi
  external:
    enabled: true

redis:
  usePassword: false
  cluster:
    enabled: false
  master:
    disableCommands: []
    service:
      type: NodePort
      nodePort: 30379
    resources:
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
    persistence:
      size: 256Mi
  slave:
    persistence:
      size: 256Mi
